Extend OF Docker image
open-formulieren/demo-extension pull request #2
Opened 2022-02-22 16:18 UTC by SilviaAmAm

Extend open forms docker image to include the demo extension.

2022-02-22 16:39 UTC, sergei-maertens commented on Dockerfile
> +USER maykin
is this needed? I'd expected the default to kick in, but maybe I'm wrong.

2022-02-22 16:41 UTC, sergei-maertens requested changes

2022-02-22 16:41 UTC, sergei-maertens commented on Dockerfile
> +
You can tidy these up :)

2022-02-22 16:41 UTC, sergei-maertens commented on docker-compose.yml
> +    image: demo-extension:6
I am curious about the magic number 6

2022-02-23 08:26 UTC, SilviaAmAm commented on docker-compose.yml
> +    image: demo-extension:6
Eh, it was my 6th attempt at making the image :P But this will have to be the name:tag of the demo_extension image

2022-02-23 08:28 UTC, SilviaAmAm commented on Dockerfile
> +USER maykin
I couldn't really figure it out, but it was the only thing that worked for having the `demo_extension` directory not owned by root:root. I tried switching to Maykin before copying, copying as root and then chown it, but it seemed to remain owned by root :thinking:

2022-02-23 08:47 UTC, sergei-maertens commented on docker-compose.yml
> +    image: demo-extension:6
if you're building locally, you can just keep building the same tag (they are mutable) :-) might save you some hassle

2022-02-23 08:48 UTC, sergei-maertens approved these changes

2022-02-23 09:16 UTC, merged